name: Docker Image CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Login to Docker Hub
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $username -p $password
 
    - name: Build the Docker image
      run: |
        ls -la
        docker build -f Docker/Dockerfile -t erzaos/apache-demo-1:latest Docker/
 
    - name: Push the Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/apache-demo-1:latest